### ISSUE TITLE
Rate limit and throttle: Last item throttled

### ISSUE THREAD

**Issue by mhulse** [zeit/async-sema#30]
Thanks for this code!

```js
const lim = RateLimit(2, {
  timeUnit: (5000),
});

await Promise.all(
  images.map(async (image, index) => {

    await lim();

    const parsed = await _prepImage.call(this, image);

    await util.downloadImage(parsed.url, parsed.target);

  })
);
```

From what I can tell, the above code downloads two images at a time and pauses 5 seconds between concurrent downloads.

I am noticing though, the last image download waits when I would like it to exit as soon as it's resolved.

In other words, since there are no more images to download (as it it the last promise to resolve) I don't want it to wait.

### Questions:

- Considering the above code snippet, am I using  `RateLimit` properly (or, is this a good use case for RateLimit)?
- How can I exit out of the last promise to resolve without pausing?

Many thanks in advance for the help and for sharing this code!

**Comment by OlliV** [comment]
I believe that's correct behavior, at least it's something that we wanted for the applications where we use the rate limiter, that are usually very long running tasks.

For downloading/uploading files I would recommend to use the semaphore primitive directly because what you usually want to do is to download/upload n files concurrently all the time, without pauses or gaps.

```js
const s = new Sema(2);
await Promise.all(
  images.map(async (image, index) => {
    await s.acquire();
    const parsed = await _prepImage.call(this, image);
    await util.downloadImage(parsed.url, parsed.target);
    s.release();
  })
);
```

or more correctly if you want to keep `s` global and never leak the tokens, then you should use

```js
try {
  await s.acquire();
  ...
} catch (err)
  ...
} finally {
  s.release();
}
```

**Comment by mhulse** [comment]
Awesome! Thank you so much @OlliV, that should do the trick for me.

I really appreciate your help!
